version: "3.7"
services:
  mysql:
    container_name: temporal-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    image: mysql:8
    networks:
      - temporal-network
    ports:
      - 7306:3306
    volumes:
      - /var/lib/mysql
  backend:
    container_name: backend
    restart: always
    environment:
      - ORCHESTRATOR_URL=ap-southeast-1.aws.api.temporal.io:7233
      - ORCHESTRATOR_API_KEY=eyJ
      - ORCHESTRATOR_NAMESPACE=pos.inedr
    networks:
      - temporal-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7200:8000    
  temporal:
    container_name: temporal
    depends_on:
      - mysql
    environment:
      - DB=mysql8
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=root
      - MYSQL_SEEDS=mysql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:1.26.2
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.26.2
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.34.0
    networks:
      - temporal-network
    ports:
      - 7080:8080
networks:
  temporal-network:
    name: temporal-network
